spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security-jwt?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl_auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL57Dialect
 # The SQL dialect makes Hibernate generate better SQL for the chosen database

security:
  jwt:
    secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    secret-key.expiration: 86400000
    secret-key.refresh-token.expiration: 604800000
    
server:
  port: 8082
  
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG